/// Flutter icons CvIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CvIcons
///      fonts:
///       - asset: fonts/CvIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CvIcons {
  CvIcons._();

  static const _kFontFam = 'CvIcons';
  static const _kFontPkg = null;

  static const IconData graduate = IconData(0xf501, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tools = IconData(0xf7d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
